# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='manager',
        ),
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
