# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:25
from __future__ import unicode_literals

import common.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MailingLists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastSentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
    ]
