# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_remove_mgr_add_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaraccess',
            name='can_send',
            field=models.BooleanField(default=False),
        ),
    ]
