# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 02:07
from __future__ import unicode_literals

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'PubSite', '0001_make_article_block'), (b'PubSite', '0002_articleblock_anchor_id')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[[b'Home', b'Home'], [b'About', b'About'], [b'Brothers', b'Brothers'], [b'Service & Activities', b'Service & Activities'], [b'Log In', b'Log In']], max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('precedence', models.IntegerField(default=0)),
                ('valid', models.BooleanField()),
                ('anchor_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
    ]
