# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0005_details_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyguest',
            name='addedBy',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
