# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 16:58
from __future__ import unicode_literals

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0008_partyguest_wasvouchedfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreylistedGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('details', models.TextField()),
            ],
            options={
                'permissions': (('manage_greylist', 'Can manage the greylist'),),
            },
            bases=(common.mixins.ModelMixin, models.Model),
        ),
    ]
