# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartyList', '0009_greylistedguest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greylistedguest',
            options={'permissions': (('can_delete_any_greylisted_guest', 'Can delete any greylsted guest'),)},
        ),
        migrations.AddField(
            model_name='greylistedguest',
            name='greylister',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
