# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0010_greylistedguest_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyguest',
            name='maybeBlacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partyguest',
            name='maybeGreylisted',
            field=models.BooleanField(default=False),
        ),
    ]
