# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0011_remember_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greylistedguest',
            old_name='greylister',
            new_name='addedBy',
        ),
    ]
