# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0012_rename_greylister'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedguest',
            name='reason',
            field=models.TextField(default='(No reason provided)'),
        ),
        migrations.AddField(
            model_name='greylistedguest',
            name='reason',
            field=models.TextField(default='(No reason provided)'),
        ),
        migrations.AlterField(
            model_name='blacklistedguest',
            name='details',
            field=models.TextField(default='(No identifying details provided)'),
        ),
        migrations.AlterField(
            model_name='greylistedguest',
            name='details',
            field=models.TextField(default='(No identifying details provided)'),
        ),
    ]
