# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0013_add_list_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyguest',
            name='maybeBlacklisted',
        ),
        migrations.RemoveField(
            model_name='partyguest',
            name='maybeGreylisted',
        ),
        migrations.AddField(
            model_name='partyguest',
            name='potentialBlacklisting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PartyList.BlacklistedGuest'),
        ),
        migrations.AddField(
            model_name='partyguest',
            name='potentialGreylisting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PartyList.GreylistedGuest'),
        ),
        migrations.AlterField(
            model_name='greylistedguest',
            name='addedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partyguest',
            name='addedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
