# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0006_default_pledgeclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bigBrother',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='big_brother', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pledgeClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='UserInfo.PledgeClass'),
        ),
    ]
