# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarship', '0002_libraryitem_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitem',
            name='course',
            field=models.CharField(blank=True, default=b'', max_length=10),
        ),
    ]
