# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarship', '0004_misc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicresource',
            name='submittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='submittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
