# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0007_change_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='calendarEmail',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
