# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0007_change_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bigBrother',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='big_brother', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='graduationYear',
            field=models.PositiveIntegerField(default=2022),
        ),
    ]
