# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0008_auto_20190321_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='iqpLon',
            new_name='iqpLong',
        ),
    ]
