# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0008_auto_20190326_1521'),
        ('UserInfo', '0008_auto_20190321_1843'),
    ]

    operations = [
    ]