# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-15 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0009_merge_20190327_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pledgeClass',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='UserInfo.PledgeClass'),
        ),
    ]
