# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0008_auto_20190326_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='iqpCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='iqpCountry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
