# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0009_merge_20190327_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='iqpLat',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='iqpLon',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='iqpCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='iqpCountry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
