# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 22:23
from __future__ import unicode_literals

import apps.PartyListV2.models
import common.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party_start', models.DateTimeField()),
                ('has_party_invite_limits', models.BooleanField(default=False)),
                ('max_party_invites', models.IntegerField(default=5)),
                ('has_preparty', models.BooleanField(default=False)),
                ('preparty_start', models.TimeField()),
                ('has_preparty_invite_limits', models.BooleanField(default=False)),
                ('max_preparty_invites', models.IntegerField(default=3)),
                ('guycount', models.IntegerField(default=0)),
                ('girlcount', models.IntegerField(default=0)),
                ('guys_ever_signed_in', models.IntegerField(default=0)),
                ('girls_ever_signed_in', models.IntegerField(default=0)),
                ('jobs', models.FileField(blank=True, null=True, upload_to=apps.PartyListV2.models.get_party_jobs_path)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'permissions': (('view_parties', 'Can view the Parties app'), ('manage_parties', 'Can manage Parties'), ('door_access', 'Has access to door check-in')),
                'default_permissions': [],
            },
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartyGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.CharField(max_length=5)),
                ('wasVouchedFor', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('signedIn', models.BooleanField(default=False)),
                ('everSignedIn', models.BooleanField(default=False)),
                ('timeFirstSignedIn', models.DateTimeField(null=True)),
                ('addedBy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_guests', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party_for_guest', to='PartyListV2.Party')),
            ],
            options={
                'verbose_name': 'Party Guest',
                'verbose_name_plural': 'Party Guests',
                'permissions': (('can_destroy_any_party_guest', 'Can Remove Any Party Guest'), ('add_party_guests', 'Can add guests to a Party')),
                'default_permissions': [],
            },
            bases=(common.mixins.ModelMixin, models.Model),
        ),
    ]
