# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyListV2', '0002_restrictedguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyguest',
            name='hasPrepartyAccess',
            field=models.BooleanField(default=False),
        ),
    ]
