# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyListV2', '0005_auto_20180509_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictedguest',
            name='cachedJSON',
            field=models.TextField(blank=True, default=''),
        ),
    ]
