# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 18:03
from __future__ import unicode_literals

import common.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartyListV2', '0008_auto_20181016_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField()),
            ],
            bases=(common.mixins.ModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='party',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='searchlogentry',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party_for_search', to='PartyListV2.Party'),
        ),
        migrations.AddField(
            model_name='searchlogentry',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
