# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyListV2', '0010_partyguest__cached_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='guest_update_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partyguest',
            name='update_counter',
            field=models.IntegerField(default=0),
        ),
    ]
