# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyListV2', '0011_auto_20181021_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restrictedguest',
            old_name='addedBy',
            new_name='added_by',
        ),
    ]
