# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 18:26
from __future__ import unicode_literals

import apps.PartyListV2.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('PartyListV2', '0013_partycountrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='jobs',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=apps.PartyListV2.models.get_party_jobs_path, verbose_name='PartyJobs'),
        ),
    ]
